version: "2.4"
networks:
  localdev:
    external: true
volumes:
  seqdata:
    external: true
  rabbitmqdata:
    external: true
services:
  rabbitmq:
    image: rabbitmq:3.9.1
    restart: unless-stopped
    volumes:
      - ./enabled_plugins:/etc/rabbitmq/enabled_plugins
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - rabbitmqdata:/var/lib/rabbitmq
    networks:
      - localdev
    ports:
      - "5672:5672"
      - "15672:15672"
  seq:
    image: datalust/seq:latest
    environment:
      ACCEPT_EULA: "Y"
      SEQ_FIRSTRUN_ADMINUSERNAME: "${DEFAULT_USERNAME:-admin}"
      SEQ_FIRSTRUN_ADMINPASSWORDHASH: FL6x1NNpca5LonfiH1pumrjVZdF2yoPW4DWPJ03VyqwnWmmErw==
    ports:
      - 9000:80
    networks:
      - localdev
    volumes:
      - seqdata:/data
    restart: unless-stopped
    mem_limit: 256m